name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.1', '7.2', '7.3', '7.4']
        laravel-version: ['5.5.*', '5.6.*', '5.7.*', '5.8.*', '6.*']
        exclude:
          - php-version: '7.1'
            larvel-version: '6.*'

    container: php:${{ matrix.php-version }}
    name: PHP ${{ matrix.php-version }} Laravel ${{ matrix.laravel-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: composer self-update --stable -n
      - run: composer require "laravel/framework:${{ matrix.laravel-version }}" --no-update -n
      - run: composer install --no-suggest --prefer-dist -n -o
      - run: vendor/bin/phpunit
